### ISSUE TITLE
Poor accuracy on FetchPickAndPlace

### ISSUE THREAD

**Issue by datonefaridze** [SudeepDasari/one_shot_transformers#10]
Hi, I couldn't set up the whole repository (that's why i asked many questions about your dataset), cloned robosuite doesn't contain setup.py file so i guess that can be a reason, also i have differnet mujoco installed, and reinstalling and adding new one is pain (i barely installed it, it's being installed globally and need to take extra actions).

So i decided to create my own dataset on gym's `FetchPickAndPlace` environment. Here is what i am doing:
1) I pick last 3 images and actions(taken after that image) as observation
2) I put finishing last 5 images as context
but it shows poor accuracy, and i was questioning if my approach was correct, because i am suspicious why model predicts 3 actions (if i feed 3 observations), why not 1.

**Comment by SudeepDasari** [comment]
Hi @datonefaridze, the network is a sequence model, so it will predict 3 actions (one for each frame). You will want to execute the last action predicted by the network. Please refer to our [paper](https://oneshotfeatures.github.io/) for more details.
