### ISSUE TITLE
Can this repo be used on real robots?

### ISSUE THREAD

**Issue by datonefaridze** [SudeepDasari/one_shot_transformers#12]
Hi, i know you have trained the model on robosuite simulated environment, i was wondering if it was possible to train the model on real robot? i have collected it, and got good results on validation dataset (loss went down to 1), but when i try to deploy it on real robot (lewansoul's xarm with 6 DOF), it fails, it just grabs the object and stops, sometimes doesn't grab it either, so it doesn't finish the task

**Comment by SudeepDasari** [comment]
This repo should work on real robots in principle. However, you may need to tune the network architecture/training loss/action space for it to work in practice.

Good luck with this effort. I always love seeing robot results 😃

**Comment by datonefaridze** [comment]
@SudeepDasari thanks, i am trying to implement it on real robot, i am tunning the network to see how it will work, let's see wat happens
