### ISSUE TITLE
ModuleNotFoundError: No module named 'robosuite.environments.baxter'

### ISSUE THREAD

**Issue by ZiyeHu** [SudeepDasari/one_shot_transformers#2]

**Comment by ZiyeHu** [comment]
How can I solve this problem? I've installed  robosuite==1.0.1.

**Comment by ZiyeHu** [comment]
The problem has been solved.

**Comment by SudeepDasari** [comment]
For installation you should use the robosuite I forked (it's changed a lot since then)

Hope you're good now!

**Comment by ZiyeHu** [comment]
Thank you for your help. 18110860007 邮箱：18110860007@fudan.edu.cn 签名由 网易邮箱大师 定制 On 11/18/2020 12:28, SudeepDasari wrote: For installation you should use the robosuite I forked (it's changed a lot since then) Hope you're good now! — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ZiyeHu** [comment]
I have already installed the robosuite you forked and collected training dataset, but I meet a new problem while I run "python path/to/one_shot_transformers/scripts/train_transformer.py path/to/one_shot_transformers/experiments/base.yaml":

one_shot_transformers/hem/datasets/agent_dataset.py", line 151, in _get_pairs image = t['obs']['image']
KeyError: 'image'

在2020-11-18 12:28:59，SudeepDasarinotifications@github.com写道：

For installation you should use the robosuite I forked (it's changed a lot since then)

Hope you're good now!

**Comment by ZiyeHu** [comment]
关于2<灭却心头火，剔起佛前灯。>0<别语愁难听>2<又匆匆过了>2年个<正轻寒轻暖漏水>人<纭越铨对另裙稳>劳动<不怕乱如麻，只怕不调查。>补<为你的安宁我内心那么凄惶>助（补<元好问>贴）<②当时制造假发的人常常买死人的头发作原料。>通<好个主人家>知，详<丈夫会应有知己，世上悠悠安足论。>情请及<惊的成绩来。>时<试问花知否>查收附<但愿苍生俱饱暖，不辞辛苦出山林。>件！<漫疑碧瓦难留>
