### ISSUE TITLE
KeyError: 'image'

### ISSUE THREAD

**Issue by ZiyeHu** [SudeepDasari/one_shot_transformers#3]
one_shot_transformers/hem/datasets/agent_dataset.py", line 151, in _get_pairs image = t['obs']['image']
KeyError: 'image'

**Comment by ZiyeHu** [comment]
I have already installed the robosuite you forked and collected training dataset, but I meet a new problem while I run "python path/to/one_shot_transformers/scripts/train_transformer.py path/to/one_shot_transformers/experiments/base.yaml":

one_shot_transformers/hem/datasets/agent_dataset.py", line 151, in _get_pairs image = t['obs']['image']
KeyError: 'image'

**Comment by SudeepDasari** [comment]
You sure you copied the sample command correctly from my README? If I had to guess you missed the `--collect_cam` while collecting data with `collect_demonstrations.py`

I hate to say this, but it works fine on my machine D: If it's still bugged on your end can you try to give me more context regarding what failed and why?
