### ISSUE TITLE
Why did you remove last frame from prediction? 

### ISSUE THREAD

**Issue by datonefaridze** [SudeepDasari/one_shot_transformers#5]
Hi, I was going though your code and couldn't figure out why did you remove the last frame from predicted mean, scale and logit? I am referring [this](https://github.com/SudeepDasari/one_shot_transformers/blob/ecd43b0c182451b67219fdbc7d6a3cd912395f17/scripts/train_transformer.py#L33) code

**Comment by SudeepDasari** [comment]
The model outputs $n$ frames (for representation learning via inverse prediction), but only have supervision for $n-1$ action predictions. However, the model outputs $n$ actions by default, so we chop off the last prediction.
