### ISSUE TITLE
can you link resources that you used for creating `DiscreteMixLogistic` ? 

### ISSUE THREAD

**Issue by datonefaridze** [SudeepDasari/one_shot_transformers#7]
Hi, I was reading this amazing [resource](https://github.com/Rayhane-mamah/Tacotron-2/issues/155)  about `DiscreteMixLogistic`, but it seems that i need to read more about it, can you link useful resources where i can learn more about this function? (i know general idea but i want learn more)

**Comment by SudeepDasari** [comment]
I explain this function fully (w/ further references) in Section 3.3 of my paper: [Transformers for One-Shot Visual Imitation](https://arxiv.org/abs/2011.05970). 

This codebase is actually an implementation of the ideas discussed in that paper, so please refer to it first if you have any other questions.
